<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $laptop     = Category::where('slug', 'laptop')->first();
        $desktop    = Category::where('slug', 'pc-desktop')->first();
        $monitor    = Category::where('slug', 'monitor')->first();
        $komponen   = Category::where('slug', 'komponen-pc')->first();
        $aksesoris  = Category::where('slug', 'aksesoris')->first();
        $jaringan   = Category::where('slug', 'jaringan')->first();

        $products = [
            // === LAPTOP ===
            [
                'category_id'    => $laptop->id,
                'name'           => 'ASUS ROG Zephyrus G14 2024',
                'slug'           => 'asus-rog-zephyrus-g14-2024',
                'description'    => 'Laptop gaming premium tipis dengan AMD Ryzen 9 dan RTX 4060.',
                'long_description' => 'ASUS ROG Zephyrus G14 adalah laptop gaming ultra-tipis terbaik dengan layar OLED 2K 120Hz. Dilengkapi prosesor AMD Ryzen 9 8945HS dan NVIDIA RTX 4060 8GB untuk performa gaming dan kreativitas tanpa kompromi.',
                'price'          => 22999000,
                'original_price' => 25999000,
                'stock'          => 15,
                'sku'            => 'ROG-G14-2024',
                'brand'          => 'ASUS',
                'is_featured'    => true,
                'rating'         => 4.8,
                'rating_count'   => 124,
                'specs'          => [
                    'Prosesor'  => 'AMD Ryzen 9 8945HS',
                    'GPU'       => 'NVIDIA RTX 4060 8GB',
                    'RAM'       => '16GB DDR5',
                    'Storage'   => '1TB NVMe SSD',
                    'Layar'     => '14" OLED 2K 120Hz',
                    'OS'        => 'Windows 11 Home',
                    'Baterai'   => '73Wh, USB-C Charging',
                ],
            ],
            [
                'category_id'    => $laptop->id,
                'name'           => 'MacBook Air M3 13-inch',
                'slug'           => 'macbook-air-m3-13-inch',
                'description'    => 'Laptop tipis dan ringan dengan chip Apple M3 terbaru.',
                'long_description' => 'MacBook Air M3 hadir dengan chip Apple M3 generasi terbaru yang memberikan performa luar biasa dengan efisiensi daya yang sangat tinggi. Layar Liquid Retina 13.6 inci dengan kecerahan hingga 500 nit.',
                'price'          => 19499000,
                'original_price' => 21000000,
                'stock'          => 8,
                'sku'            => 'MBA-M3-13',
                'brand'          => 'Apple',
                'is_featured'    => true,
                'rating'         => 4.9,
                'rating_count'   => 256,
                'specs'          => [
                    'Prosesor'  => 'Apple M3 8-core CPU',
                    'GPU'       => 'Apple M3 10-core GPU',
                    'RAM'       => '8GB Unified Memory',
                    'Storage'   => '256GB SSD',
                    'Layar'     => '13.6" Liquid Retina',
                    'OS'        => 'macOS Sonoma',
                    'Baterai'   => '52.6Wh, 18 jam',
                ],
            ],
            [
                'category_id'    => $laptop->id,
                'name'           => 'Lenovo ThinkPad X1 Carbon Gen 12',
                'slug'           => 'lenovo-thinkpad-x1-carbon-gen-12',
                'description'    => 'Laptop bisnis ultra-tipis dengan keandalan enterprise.',
                'long_description' => 'ThinkPad X1 Carbon Gen 12 adalah pilihan ideal untuk profesional bisnis. Ringan hanya 1.12kg dengan sertifikasi MIL-SPEC, layar IPS 14 inci Anti-Glare, dan keyboard ThinkPad yang legendaris.',
                'price'          => 24500000,
                'original_price' => null,
                'stock'          => 5,
                'sku'            => 'TP-X1C-G12',
                'brand'          => 'Lenovo',
                'is_featured'    => false,
                'rating'         => 4.7,
                'rating_count'   => 67,
                'specs'          => [
                    'Prosesor'  => 'Intel Core Ultra 7 165U',
                    'GPU'       => 'Intel Arc Graphics',
                    'RAM'       => '16GB LPDDR5X',
                    'Storage'   => '512GB NVMe SSD',
                    'Layar'     => '14" IPS Anti-Glare 2.8K',
                    'OS'        => 'Windows 11 Pro',
                    'Berat'     => '1.12 kg',
                ],
            ],
            [
                'category_id'    => $laptop->id,
                'name'           => 'ASUS VivoBook 15 OLED',
                'slug'           => 'asus-vivobook-15-oled',
                'description'    => 'Laptop harian dengan layar OLED premium harga terjangkau.',
                'long_description' => 'VivoBook 15 OLED hadir dengan layar OLED 15.6 inci yang memukau dengan akurasi warna PANTONE Validated. Performa Intel Core i5 yang handal untuk aktivitas sehari-hari.',
                'price'          => 8999000,
                'original_price' => 10499000,
                'stock'          => 22,
                'sku'            => 'VB15-OLED',
                'brand'          => 'ASUS',
                'is_featured'    => true,
                'rating'         => 4.5,
                'rating_count'   => 189,
                'specs'          => [
                    'Prosesor'  => 'Intel Core i5-13500H',
                    'GPU'       => 'Intel Iris Xe',
                    'RAM'       => '8GB DDR4',
                    'Storage'   => '512GB NVMe SSD',
                    'Layar'     => '15.6" OLED FHD 60Hz',
                    'OS'        => 'Windows 11 Home',
                ],
            ],

            // === PC DESKTOP ===
            [
                'category_id'    => $desktop->id,
                'name'           => 'PC Gaming Ryzen 7 7700X + RTX 4070',
                'slug'           => 'pc-gaming-ryzen-7-7700x-rtx-4070',
                'description'    => 'PC gaming rakitan high-end untuk 1440p gaming ultra.',
                'long_description' => 'Paket PC gaming lengkap dengan AMD Ryzen 7 7700X dan NVIDIA RTX 4070 12GB. Siap untuk gaming 1440p dengan frame rate tinggi di semua game AAA terbaru. Sudah termasuk casing, PSU, dan sistem pendingin.',
                'price'          => 18500000,
                'original_price' => 20000000,
                'stock'          => 7,
                'sku'            => 'PC-R7-RTX4070',
                'brand'          => 'TechnoStore Build',
                'is_featured'    => true,
                'rating'         => 4.9,
                'rating_count'   => 43,
                'specs'          => [
                    'Prosesor'  => 'AMD Ryzen 7 7700X',
                    'GPU'       => 'NVIDIA RTX 4070 12GB',
                    'RAM'       => '32GB DDR5 6000MHz',
                    'Storage'   => '1TB NVMe Gen4 SSD',
                    'Motherboard' => 'ASUS ROG STRIX B650-A',
                    'PSU'       => 'Seasonic Focus GX 750W',
                    'Casing'    => 'Lian Li Lancool 216',
                ],
            ],
            [
                'category_id'    => $desktop->id,
                'name'           => 'PC Office Intel Core i3 Gen 13',
                'slug'           => 'pc-office-intel-core-i3-gen13',
                'description'    => 'PC kantor handal dan hemat daya untuk produktivitas.',
                'long_description' => 'PC Office yang ideal untuk pekerjaan kantor sehari-hari. Intel Core i3-13100 yang efisien, RAM 8GB, dan SSD 256GB untuk loading yang cepat. Sudah termasuk casing mini-tower yang rapi.',
                'price'          => 5200000,
                'original_price' => null,
                'stock'          => 12,
                'sku'            => 'PC-I3-13-OFF',
                'brand'          => 'TechnoStore Build',
                'is_featured'    => false,
                'rating'         => 4.4,
                'rating_count'   => 28,
                'specs'          => [
                    'Prosesor'  => 'Intel Core i3-13100',
                    'GPU'       => 'Intel UHD Graphics 730',
                    'RAM'       => '8GB DDR4 3200MHz',
                    'Storage'   => '256GB SATA SSD',
                    'Motherboard' => 'Gigabyte H610M',
                    'PSU'       => 'Seasonic B12 500W',
                ],
            ],

            // === MONITOR ===
            [
                'category_id'    => $monitor->id,
                'name'           => 'LG UltraGear 27GP850-B 165Hz QHD',
                'slug'           => 'lg-ultragear-27gp850-b-165hz-qhd',
                'description'    => 'Monitor gaming IPS QHD 165Hz dengan respons 1ms.',
                'long_description' => 'Monitor gaming terbaik untuk esport dan gaming AAA. Panel IPS dengan resolusi QHD 2560x1440, refresh rate 165Hz, dan waktu respons 1ms GtG. Didukung NVIDIA G-Sync Compatible dan AMD FreeSync Premium.',
                'price'          => 4599000,
                'original_price' => 5299000,
                'stock'          => 18,
                'sku'            => 'LG-27GP850',
                'brand'          => 'LG',
                'is_featured'    => true,
                'rating'         => 4.8,
                'rating_count'   => 312,
                'specs'          => [
                    'Panel'         => 'IPS',
                    'Resolusi'      => '2560x1440 (QHD)',
                    'Refresh Rate'  => '165Hz',
                    'Waktu Respons' => '1ms GtG',
                    'HDR'           => 'HDR10',
                    'Koneksi'       => '2x HDMI 2.0, 1x DP 1.4',
                    'Ukuran'        => '27 inci',
                ],
            ],
            [
                'category_id'    => $monitor->id,
                'name'           => 'Dell UltraSharp U2723D 27" 4K IPS',
                'slug'           => 'dell-ultrasharp-u2723d-27-4k-ips',
                'description'    => 'Monitor profesional 4K IPS Black untuk desain grafis.',
                'long_description' => 'Monitor profesional dengan panel IPS Black eksklusif Dell yang menghadirkan kontras rasio 2000:1, jauh lebih tinggi dari IPS standar. Resolusi 4K UHD ideal untuk desainer, fotografer, dan editor video.',
                'price'          => 8900000,
                'original_price' => null,
                'stock'          => 6,
                'sku'            => 'DELL-U2723D',
                'brand'          => 'Dell',
                'is_featured'    => false,
                'rating'         => 4.7,
                'rating_count'   => 89,
                'specs'          => [
                    'Panel'         => 'IPS Black',
                    'Resolusi'      => '3840x2160 (4K UHD)',
                    'Refresh Rate'  => '60Hz',
                    'Warna'         => '100% sRGB, 98% DCI-P3',
                    'Koneksi'       => 'HDMI 2.0, DP 1.4, USB-C 90W',
                    'Ukuran'        => '27 inci',
                ],
            ],

            // === KOMPONEN PC ===
            [
                'category_id'    => $komponen->id,
                'name'           => 'NVIDIA GeForce RTX 4070 Super 12GB',
                'slug'           => 'nvidia-geforce-rtx-4070-super-12gb',
                'description'    => 'VGA card terbaik untuk gaming 1440p dan kreativitas.',
                'long_description' => 'RTX 4070 Super hadir dengan 12GB GDDR6X dan arsitektur Ada Lovelace terbaru. Performa 1440p yang luar biasa dengan DLSS 3 Frame Generation dan Ray Tracing generasi ke-3.',
                'price'          => 9800000,
                'original_price' => 10500000,
                'stock'          => 9,
                'sku'            => 'RTX4070S-12G',
                'brand'          => 'NVIDIA',
                'is_featured'    => true,
                'rating'         => 4.9,
                'rating_count'   => 156,
                'specs'          => [
                    'VRAM'       => '12GB GDDR6X',
                    'CUDA Cores' => '7168',
                    'TDP'        => '220W',
                    'Koneksi'    => '3x DP 1.4, 1x HDMI 2.1',
                    'Panjang'    => '336mm',
                ],
            ],
            [
                'category_id'    => $komponen->id,
                'name'           => 'Kingston FURY Beast DDR5 32GB 6000MHz',
                'slug'           => 'kingston-fury-beast-ddr5-32gb-6000mhz',
                'description'    => 'RAM DDR5 super cepat 6000MHz untuk platform Intel & AMD.',
                'long_description' => 'Kingston FURY Beast DDR5 dengan frekuensi 6000MHz CL36 memberikan bandwidth tinggi yang dibutuhkan prosesor modern. Kompatibel dengan Intel XMP 3.0 dan AMD EXPO.',
                'price'          => 1850000,
                'original_price' => 2100000,
                'stock'          => 35,
                'sku'            => 'KF-DDR5-32G',
                'brand'          => 'Kingston',
                'is_featured'    => false,
                'rating'         => 4.7,
                'rating_count'   => 203,
                'specs'          => [
                    'Kapasitas' => '32GB (2x16GB)',
                    'Tipe'      => 'DDR5',
                    'Frekuensi' => '6000MHz',
                    'Latency'   => 'CL36',
                    'Profil'    => 'XMP 3.0, EXPO',
                ],
            ],
            [
                'category_id'    => $komponen->id,
                'name'           => 'Samsung 990 Pro NVMe SSD 1TB',
                'slug'           => 'samsung-990-pro-nvme-ssd-1tb',
                'description'    => 'SSD NVMe PCIe 4.0 tercepat dengan read 7450 MB/s.',
                'long_description' => 'Samsung 990 Pro adalah SSD NVMe PCIe 4.0 paling cepat dengan kecepatan baca sequensial hingga 7450 MB/s. Hadir dengan fitur Dynamic Thermal Guard untuk menjaga performa tetap optimal.',
                'price'          => 1499000,
                'original_price' => 1799000,
                'stock'          => 28,
                'sku'            => 'SAM-990PRO-1T',
                'brand'          => 'Samsung',
                'is_featured'    => false,
                'rating'         => 4.8,
                'rating_count'   => 445,
                'specs'          => [
                    'Kapasitas'   => '1TB',
                    'Interface'   => 'PCIe 4.0 x4 NVMe',
                    'Read Seq'    => '7450 MB/s',
                    'Write Seq'   => '6900 MB/s',
                    'Endurance'   => '600 TBW',
                    'Garansi'     => '5 tahun',
                ],
            ],
            [
                'category_id'    => $komponen->id,
                'name'           => 'AMD Ryzen 9 7950X Processor',
                'slug'           => 'amd-ryzen-9-7950x-processor',
                'description'    => 'Prosesor flagship AMD 16-core untuk workstation dan gaming.',
                'long_description' => 'AMD Ryzen 9 7950X adalah prosesor flagship dengan 16 core dan 32 thread, boost hingga 5.7GHz. Performa workstation dan rendering yang luar biasa dengan arsitektur Zen 4.',
                'price'          => 8999000,
                'original_price' => null,
                'stock'          => 4,
                'sku'            => 'AMD-R9-7950X',
                'brand'          => 'AMD',
                'is_featured'    => false,
                'rating'         => 4.9,
                'rating_count'   => 78,
                'specs'          => [
                    'Core/Thread' => '16C / 32T',
                    'Base Clock'  => '4.5 GHz',
                    'Boost Clock' => '5.7 GHz',
                    'TDP'         => '170W',
                    'Socket'      => 'AM5',
                    'Cache'       => '80MB',
                ],
            ],

            // === AKSESORIS ===
            [
                'category_id'    => $aksesoris->id,
                'name'           => 'Logitech G Pro X Superlight 2',
                'slug'           => 'logitech-g-pro-x-superlight-2',
                'description'    => 'Mouse gaming wireless paling ringan untuk esport.',
                'long_description' => 'G Pro X Superlight 2 adalah mouse gaming wireless yang hanya 60 gram dengan sensor HERO 2 25K DPI. Koneksi LIGHTSPEED tanpa delay dengan baterai hingga 95 jam.',
                'price'          => 1599000,
                'original_price' => 1899000,
                'stock'          => 30,
                'sku'            => 'LG-GPXSL2',
                'brand'          => 'Logitech',
                'is_featured'    => true,
                'rating'         => 4.8,
                'rating_count'   => 534,
                'specs'          => [
                    'Sensor'    => 'HERO 2 25K',
                    'DPI'       => '100 - 25,600',
                    'Bobot'     => '60g',
                    'Koneksi'   => 'LIGHTSPEED Wireless / USB',
                    'Baterai'   => '95 jam',
                    'Tombol'    => '5 tombol',
                ],
            ],
            [
                'category_id'    => $aksesoris->id,
                'name'           => 'Keychron K2 Pro Wireless Mechanical Keyboard',
                'slug'           => 'keychron-k2-pro-wireless-mechanical-keyboard',
                'description'    => 'Keyboard mekanikal wireless compact 75% hot-swappable.',
                'long_description' => 'Keychron K2 Pro adalah keyboard mekanikal 75% yang mendukung Bluetooth 5.1 multi-device dan koneksi USB-C. Fitur hot-swappable memungkinkan ganti switch tanpa solder.',
                'price'          => 1299000,
                'original_price' => null,
                'stock'          => 20,
                'sku'            => 'KC-K2PRO',
                'brand'          => 'Keychron',
                'is_featured'    => false,
                'rating'         => 4.7,
                'rating_count'   => 276,
                'specs'          => [
                    'Layout'    => '75% (84 keys)',
                    'Switch'    => 'Gateron G Pro Red (Hot-swap)',
                    'Koneksi'   => 'Bluetooth 5.1 / USB-C',
                    'Baterai'   => '4000mAh',
                    'Backlight' => 'RGB',
                    'OS'        => 'Windows / macOS',
                ],
            ],
            [
                'category_id'    => $aksesoris->id,
                'name'           => 'HyperX Cloud Alpha Wireless Headset',
                'slug'           => 'hyperx-cloud-alpha-wireless-headset',
                'description'    => 'Headset gaming wireless dengan baterai 300 jam tahan lama.',
                'long_description' => 'HyperX Cloud Alpha Wireless adalah headset gaming dengan baterai tahan hingga 300 jam yang luar biasa. Driver 50mm Custom dengan suara yang kaya dan mikrofon noise-cancelling yang dapat dilepas.',
                'price'          => 1999000,
                'original_price' => 2399000,
                'stock'          => 14,
                'sku'            => 'HX-CLOUD-AW',
                'brand'          => 'HyperX',
                'is_featured'    => false,
                'rating'         => 4.6,
                'rating_count'   => 167,
                'specs'          => [
                    'Driver'        => '50mm Custom',
                    'Frekuensi'     => '15Hz – 21kHz',
                    'Koneksi'       => '2.4GHz Wireless',
                    'Baterai'       => '300 jam',
                    'Mikrofon'      => 'Cardioid, detachable',
                    'Kompatibel'    => 'PC, PS4/PS5',
                ],
            ],

            // === JARINGAN ===
            [
                'category_id'    => $jaringan->id,
                'name'           => 'TP-Link Archer AXE300 WiFi 6E Router',
                'slug'           => 'tp-link-archer-axe300-wifi-6e-router',
                'description'    => 'Router WiFi 6E Tri-Band dengan kecepatan hingga 19 Gbps.',
                'long_description' => 'Archer AXE300 adalah router WiFi 6E pertama TP-Link yang mendukung band 6GHz untuk koneksi ultra-cepat dengan gangguan minimal. Kecepatan kombinasi hingga 19.8 Gbps untuk seluruh rumah.',
                'price'          => 3299000,
                'original_price' => null,
                'stock'          => 10,
                'sku'            => 'TP-AXE300',
                'brand'          => 'TP-Link',
                'is_featured'    => false,
                'rating'         => 4.6,
                'rating_count'   => 92,
                'specs'          => [
                    'Standard'  => 'WiFi 6E (802.11ax)',
                    'Band'      => 'Tri-Band (2.4+5+6GHz)',
                    'Speed'     => 'Up to 19.8 Gbps',
                    'Antena'    => '12 antena eksternal',
                    'Port'      => '1x 10G WAN, 4x 2.5G LAN',
                ],
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
